// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	dtos "velocity-technical-test/internal/domain/orders/dtos"

	mock "github.com/stretchr/testify/mock"
)

// IOrderUseCase is an autogenerated mock type for the IOrderUseCase type
type IOrderUseCase struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: orderDTO, indempotenciaKey
func (_m *IOrderUseCase) CreateOrder(orderDTO dtos.OrderDTO, indempotenciaKey string) error {
	ret := _m.Called(orderDTO, indempotenciaKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.OrderDTO, string) error); ok {
		r0 = rf(orderDTO, indempotenciaKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderWithItems provides a mock function with given fields: orderID
func (_m *IOrderUseCase) GetOrderWithItems(orderID uint) (*dtos.OrderDTO, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderWithItems")
	}

	var r0 *dtos.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dtos.OrderDTO, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(uint) *dtos.OrderDTO); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.OrderDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOrderUseCase creates a new instance of IOrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderUseCase {
	mock := &IOrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
