
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_management
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - mynetwork

  cam_service:
    image: cam1993/cam:velocity
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DB_NAME: order_management
      MYSQL_DB_USER: mysql
      MYSQL_DB_PASSWORD: mysql
      SERVER_PORT: 60000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "60000:60000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
